### ISSUE TITLE
Reduce unnecessary hot write region scheduling during rolling upgrade TiKV

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3050]
### Describe your feature request related problem
In some cases, more operators are generated than usual when rolling upgrade TiKV：
![image](https://user-images.githubusercontent.com/6428910/95484990-baab6700-09c3-11eb-9b77-925d8df1ba70.png)
![image](https://user-images.githubusercontent.com/6428910/95485139-e7f81500-09c3-11eb-81d8-642311a5deb9.png)
and the latency will increase and the compaction flow will increase that caused by scheduling, esapeically the disk perfromance is not very good. see  below (The time zone is different, but it is the same time period):
![image](https://user-images.githubusercontent.com/6428910/95485562-808e9500-09c4-11eb-9d83-310581d81e9e.png)

### Describe the feature you'd like
reduce the unnecessary scheduling.

### Describe alternatives you've considered
we can let the restart TiKV have a slow start process, especially in the hot region scheduler. and restart TiKV may have some statistics issues, it can reduce the jitter caused by statistical errors can be reduced.

### Teachability, Documentation, Adoption, Migration Strategy
- Go

**Comment by zz-jason** [comment]
> In some cases, more operators are generated than usual when rolling upgrade TiKV

We need to find the reasons.

**Comment by lhy1024** [comment]
Maybe we should make pd know that the cluster is currently in rolling upgrade and increase the scheduling limit to reduce unnecessarily scheduling

**Comment by lhy1024** [comment]
Whether is it more suitable to close the hot scheduler during rolling upgrade TiKV

**Comment by disksing** [comment]
> Maybe we should make pd know that the cluster is currently in rolling upgrade and increase the scheduling limit to reduce unnecessarily scheduling

increase ->decrease?

**Comment by lhy1024** [comment]
> > Maybe we should make pd know that the cluster is currently in rolling upgrade and increase the scheduling limit to reduce unnecessarily scheduling
> 
> increase ->decrease?

yep

**Comment by nolouch** [comment]
after https://github.com/tikv/pd/pull/3200, the move hot peer operator is reduced, close this issue.

**Comment by HunDunDM** [comment]
In the current strategy, there are three main considerations for hotspot scheduling:
* store write rate = sum(__peer__ write rate), it will create `hot-write-move-peer`
* store leader write rate = sum(__leader__ write rate), it will create `hot-write-transfer-leader`
* store read rate = sum(__leader__ read rate), it will create `hot-read-move-peer` and `hot-read-transfer-leader`

When rolling restart TiKV, we will evict the leader. It will cause the stability of the leader of all stores to be broken. Therefore, some `hot-write-transfer-leader`, `hot-read-move-peer` and `hot-read-transfer-leader` are necessary. But it will not cause the stability of the peers' write rate of all stores to be broken, so there should not be a lot of `hot-write-move-peer`.

Before #3200 , the statistics of the store will be dropped when restarting, it accidents caused the stability of the peers' write rate of all stores to be broken.

Here are some comparisons:

* Store statistics
  * Before
![image](https://user-images.githubusercontent.com/19789302/102318099-b8611c80-3fb3-11eb-9e19-eabf7558d39c.png)
![image](https://user-images.githubusercontent.com/19789302/102319427-d039a000-3fb5-11eb-8a19-788f86234178.png)
  * After
![image](https://user-images.githubusercontent.com/19789302/102319628-27d80b80-3fb6-11eb-8f2a-94189521c823.png)
![image](https://user-images.githubusercontent.com/19789302/102319684-36bebe00-3fb6-11eb-8f02-003932c08958.png)
* SQL QPS
  * Before
![image](https://user-images.githubusercontent.com/19789302/102318248-ff4f1200-3fb3-11eb-8e3e-7e01b72f2edb.png)
  * After
![image](https://user-images.githubusercontent.com/19789302/102319818-666dc600-3fb6-11eb-92d9-0ca67621b98f.png)
* Sum of `move-peer` operator
  * Before
![image](https://user-images.githubusercontent.com/19789302/102318453-4f2dd900-3fb4-11eb-85b8-3f1f3e9ced1e.png)
  * After
![image](https://user-images.githubusercontent.com/19789302/102319982-a765da80-3fb6-11eb-8a9d-47c8f3069a5b.png)
* TiKV duration
  * Before
![image](https://user-images.githubusercontent.com/19789302/102321681-f9a7fb00-3fb8-11eb-8ab8-2a9c786ef45f.png)
  * After
![image](https://user-images.githubusercontent.com/19789302/102321803-278d3f80-3fb9-11eb-88e2-647539516ef0.png)

**Comment by HunDunDM** [comment]
In the current strategy, there are three main considerations for hotspot scheduling:

* store write rate = sum(__peer__ write rate), it will create `hot-write-move-peer`
* store leader write rate = sum(__leader__ write rate), it will create `hot-write-transfer-leader`
* store read rate = sum(__leader__ read rate), it will create `hot-read-move-peer` and `hot-read-transfer-leader`

When rolling restart TiKV, we will evict the leader. It will cause the stability of the leader of all stores to be broken. Therefore, some `hot-write-transfer-leader`, `hot-read-move-peer` and `hot-read-transfer-leader` are necessary. But it will not cause the stability of the peers' write rate of all stores to be broken, so there should not be a lot of `hot-write-move-peer`.

Before #3200 , the statistics of the store will be dropped when restarting, it accidents caused the stability of the peers' write rate of all stores to be broken.

Here are some comparisons (release v4.0.9):

* Store statistics
  * The value of store-write-rate-bytes will no longer fall off the bottom.
  * ![image](https://user-images.githubusercontent.com/19789302/102972274-c07e0680-4535-11eb-89a1-4b928e86e311.png)
  * The value of store-read-rate-bytes will still fall to the bottom. This is because there is no leader at that moment.
  * ![image](https://user-images.githubusercontent.com/19789302/102972479-118dfa80-4536-11eb-9b3f-a9e009afc27a.png)
* Sum of `move-peer` operator
  * `hot-read-move-peer + hot-write-move-peer` is reduced from `35 + 31 = 66` to `54 + 0 = 54`. (Their names in `release-4.0` are slightly different from `master`.)
  * No `hot-write-move-peer` is created during rolling restart.
  * ![image](https://user-images.githubusercontent.com/19789302/102972824-a3960300-4536-11eb-8e32-5b4667efc323.png)
* TiKV duration
  * ![image](https://user-images.githubusercontent.com/19789302/102973136-3636a200-4537-11eb-906a-02bf03a8fc5a.png)
  * ![image](https://user-images.githubusercontent.com/19789302/102973231-59f9e800-4537-11eb-8fc2-fade81757d1d.png)
* QPS
  * ![image](https://user-images.githubusercontent.com/19789302/102971945-42b9fb00-4535-11eb-972b-4c3dad559c44.png)
  * Base
    | | |
    | :-- | -- |
    | tps | 17455.70 |
    | tps-jitter-sd | 7.66% |
    | tps-jitter-kmean(k=2) | 27.88% |
    | tps-jitter-rand-percent(p=10.00%) | 4.81% |
    | p99-lat | 100.69ms |
    | p99-lat-jitter-sd | 44.28% |
    | p99-lat-jitter-kmean(k=2) | 146.49% |
    | p99-lat-jitter-rand-percent(p=10.00%) | 29.66% |
  * Before
    | | |
    | :-- | -- |
    | tps | 16088.32 |
    | tps-jitter-sd | 20.29% |
    | tps-jitter-kmean(k=2) | 62.65% |
    | tps-jitter-rand-percent(p=10.00%) | 15.54% |
    | p99-lat | 183.97ms|
    | p99-lat-jitter-sd | 507.22% |
    | p99-lat-jitter-kmean(k=2) | 2862.16% |
    | p99-lat-jitter-rand-percent(p=10.00%) | 74.23% |
  * After
    | | |
    | :-- | -- |
    | tps | 16864.37 |
    | tps-jitter-sd | 14.96% |
    | tps-jitter-kmean(k=2) | 59.01% |
    | tps-jitter-rand-percent(p=10.00%) | 8.36% |
    | p99-lat | 103.37ms |
    | p99-lat-jitter-sd | 352.09% |
    | p99-lat-jitter-kmean(k=2)|2240.71% |
    | p99-lat-jitter-rand-percent(p=10.00%)|27.73% |

**Comment by HunDunDM** [comment]
We can continue to optimize `hot-read-move-peer` in the future.

**Comment by lhy1024** [comment]
> In the current strategy, there are three main considerations for hotspot scheduling:

LGTM

**Comment by disksing** [comment]
@zhangjinpeng1987 Please take another look!
