### ISSUE TITLE
Provide HTTP API and gRPC API for Keyspace

### ISSUE THREAD

**Issue by andylokandy** [tikv/pd#3216]
The basic management of Keyspace is handled by HTTP API. It includes adding a new Keyspace, removing a given Keyspace, updating the prefix or mode for a Keyspace. 

The source code of HTTP API is located in `routers.go`.

```typescript
GET /keyspaces
returns [{id: Int, name: String, mode: ["Transaction" | "Raw"]}]

GET /keyspaces/{name}
returns {id: Int, name: String, mode: ["Transaction" | "Raw"]}

POST /keyspaces
// allocate an id if id is not given
body {id: Int?, name: String, mode: ["Transaction" | "Raw"]}
returns {id: Int, name: String, mode: ["Transaction" | "Raw"]}

DELETE /keyspaces/{name}
```

The client queries Keyspace information in gRPC. So RPC `GetKeySpace` is introduced.

```protobuf
rpc GetKeySpace(GetKeySpaceRequest) returns (GetKeySpaceResponse) {}

message GetKeyspaceRequest {
    RequestHeader header = 1;

    string name = 2;
}

message GetKeyspaceResponse {
    ResponseHeader header = 1;

     string name = 2;
     uint64 id = 3;
     KeyspaceMode mode = 4;
}

enum KeyspaceMode {
    Raw = 1;
    Transaction = 2;
}
```

**Comment by gregwebs** [comment]
This is missing the prefix. This is [described in the RFC](https://github.com/tikv/rfcs/blob/3b712bbeb4e276a34f2faefb0a428d3677171338/text/2020-01-30-key-spaces.md).

**Comment by andylokandy** [comment]
Keyspace id is the prefix in your word.

**Comment by gregwebs** [comment]
The id here is an int but a prefix is binary

**Comment by andylokandy** [comment]
Yes, the id will be encoded into var-int as the prefix.

**Comment by gregwebs** [comment]
We talked about this and I am fine with this approach. Since the prefix cannot be changed it can be treated as an ID. It can be pretty printed as an int or binary depending on a user's preference and in some cases printed as text.

It is a little awkward to get back an int from the GET keyspace call because the client actually needs the binary form so either needs to get at the un-decoded value (which libraries attempt to hide) or re-decode it. But we can consider modifying the interface slightly after trying out some implementation.

**Comment by andylokandy** [comment]
see the lastest tracking issue: https://github.com/tikv/pd/issues/3214
