### ISSUE TITLE
Update etcd to v3.5.x

### ISSUE THREAD

**Issue by disksing** [tikv/pd#3877]
## Development Task

[etcd v3.5.0](https://etcd.io/docs/v3.5/) is the latest stable release version which is also go mod compatible version when used as a library. As there are other applications and libraries using pd (or pd client) as a library, we should upgrade etcd to v3.5.0 to make it more community-friendly.

There was an attempt before https://github.com/tikv/pd/pull/3873. But we cannot merge it because upgrading the tidb-dashboard's etcd will break the PD of the release branches since the PDs of the different branches all depend on the release branch's tidb-dashboard.

Therefore, before upgrading etcd, we need to resolve the dependency between pd and tidb-dashboard. Specifically, create separate go mods for pd and pd-server, so that only pd-server will depend on tidb-dashboard and we can upgrade pd without upgrading tidb-dashboard.

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/issues/3847

**Comment by maoueh** [comment]
I would like to see how this can be pushed faster. Right now depending on tikv client-go is really a pain because for example, we are completely unable to perform a `go mod tidy` in our project due to problem with the infamous `etcd` library dependencies.

It would be more than welcome that this is done sooner than later. Willing to help if some hands are required.
