### ISSUE TITLE
Replace juju/ratelimit

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4206]
## Development Task
we need to replace juju/ratelimit, consider one:
 - [golang.org/x/time/rate](https://pkg.go.dev/golang.org/x/time/rate)
 - [uber-go/ratelimit](https://github.com/uber-go/ratelimit)

**Comment by matchge-ca** [comment]
Some updates for the comparison of two candidates:

There are two classic traffic policing algorithms which can be used for rate limit implementations, token bucket and leaky bucket. Some of the major differences between these two algorithms are:
- Token bucket algorithm allows traffic as long as there is enough allowance(tokens) at a burst rate, while leaky bucket algorithm converts bursty traffic into steady, continuous traffic at a static rate. 
- Token bucket will either block, hold(wait) or drop the traffic if there is not enough token in the bucket, however the leaky bucket allows outgoing traffic at a finite rate.

The **golang.org/x/time/rate** package is implemented based on token bucket algorithm, same as **juju/ratelimit**, and the **uber-go/ratelimit** is implemented based on the leaky bucket algorithm. 

Due to the same algorithm, both **juju/ratelimit** and **golang.org/x/time/rate** packages provide similar concepts such as bucket, available tokens, rate and last timestamp etc. However, there are also many differences in the implementation details, such as:
- how to handle burst traffic
- how token generate rate is calculated 
- the behavior of wait is different

These differences will be evaluated and covered in tests, and also need a proper way to quantify the behavior difference (More details will be provided later).

**Summarize: To minimize the behavior difference, code changes and impact scope, I suggest to choose **golang.org/x/time/rate** as the candidate.** More information will be provided once replacement implementation is completed.

**Comment by nolouch** [comment]
Ok, let's use`golang.org/x/time/rate` to replace it.
