### ISSUE TITLE
Delete `isolationLevel` and `locationLabels` from placement rules

### ISSUE THREAD

**Issue by xhebox** [tikv/pd#4540]
### Describe your feature request related problem

Refer https://github.com/pingcap/tidb/issues/31052, maybe delete `isolationLevel` and `locationLabels` from placement rules. And just use the global configuration.

**Comment by CalvinNeo** [comment]
Currently, TiFlash rely on `ALTER TABLE table_name SET TIFLASH REPLICA count LOCATION LABELS location_labels`, which can [specify location labels for TiFlash](https://docs.pingcap.com/zh/tidb/stable/use-tiflash/).

I think a global configuration may not overrides TiFlash's location labels configuration, otherwise it may lead to a  behavior change.

**Comment by nolouch** [comment]
Which scenario will use this syntax? Does TiKV is consist with TiFlash?
