### ISSUE TITLE
5.2.3 upgrade to 5.2.4, trace-region-flow config is deleted

### ISSUE THREAD

**Issue by seiya-annie** [tikv/pd#4841]
## Bug Report

1. install v5.2.3 with default config
2. use tiup ctl:v5.2.4 pd -u http://172.16.5.101:2379 config show all to check pd configs
3. upgrade to v5.2.4
4. check 5.2.4 config with 5.2.3

### What did you see instead?

trace-region-flow config removed from pd-server config set 

"pd-server": {
    "use-region-storage": "true",
    "max-gap-reset-ts": "24h0m0s",
    "key-type": "table",
    "runtime-services": "",
    "metric-storage": "",
    "dashboard-address": "http://172.16.5.101:2379",
    "flow-round-by-digit": 3
  },

### What version of PD are you using (`pd-server -V`)?
[tidb@101 bin]$ ./pd-server -V
Release Version: v5.2.4
Edition: Community
Git Commit Hash: 35a202d9240106cc19b9b0fb07b6ad9ff380613b
Git Branch: heads/refs/tags/v5.2.4
UTC Build Time:  2022-04-18 02:53:38
[tidb@101 bin]$

**Comment by mayjiang0203** [comment]
By design, not a bug, here is the description in docs:

If you have upgraded your cluster from a TiDB 4.0 version to the current version, the behavior of flow-round-by-digit after the upgrading and the behavior of trace-region-flow before the upgrading are consistent by default. This means that if the value of trace-region-flow is false before the upgrading, the value of flow-round-by-digit after the upgrading is 127; if the value of trace-region-flow is true before the upgrading, the value of flow-round-by-digit after the upgrading is 3.
