### ISSUE TITLE
Online progress hung in 83% when scale out with imbalance labels

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#5234]
### What did you do?
Cluster Config:
![ZO745v59e0](https://user-images.githubusercontent.com/9443637/175857486-631bffed-e42b-4c6b-b0e8-709e1b7423b5.jpg)

![usl19PhI0e](https://user-images.githubusercontent.com/9443637/175857419-e98af608-141d-427c-9108-f1069ef01233.jpg)

Scale out topo:
![U8RSQz6Fkq](https://user-images.githubusercontent.com/9443637/175857460-a736f274-bacb-42cc-bec0-599b6722d74c.jpg)

### What did you expect to see?
When balance stop, preparing should stop also. 

### What did you see instead?
No balance operator created more than 1 hours, but online store progress still stay in 83%.

![image](https://user-images.githubusercontent.com/9443637/175857788-38898f20-8fce-4e20-b4ea-2c521e30ce2a.png)

### What version of PD are you using (`pd-server -V`)?
master

**Comment by rleungx** [comment]
This is because we only have 1 replica in each DC, the zone label doesn't take effect. The data in a DC is evenly distributed. But when we calculate the topology weight, it won't filter the invalid label level. The topology weight in the DC1 is 2:1:1 instead of 1:1:1, which makes the progress calculation inaccurate. A possible workaround is to change the location label to DC only since the other labels do not take effect.
