### ISSUE TITLE
qps dorp to zero after pdleader network partition

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#6053]
### What did you do?
https://tcms.pingcap.net/dashboard/executions/plan/1680848
https://tcms.pingcap.net/dashboard/executions/plan/1680811
deploy with 3 pds
1、run tpcc 
2、run ha-pdleader-to-all-network-partition-last-for-10m

### What did you expect to see?
qps can recover in 2min when inject pd leader network partition

### What did you see instead?
qps dorp to zero after pdleader network partition
![image](https://user-images.githubusercontent.com/84712107/221509342-73966b7f-ac1d-4ff3-863a-ce9309c98d14.png)

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: b2f2a8219a401cb64353bbdc53968d0133419c8a
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:  2023-02-24 11:32:41

**Comment by bufferflies** [comment]
@lhy1024，The root cause is  this [pr](https://github.com/tikv/pd/commit/833e5fc741e1460e3d2037c2b5c32f836e4594d1)
before
![bacf3536-3b48-4328-a92b-6f86954633d1](https://user-images.githubusercontent.com/23159587/221740853-e03759c2-6fb9-4c33-ac07-4d6cd857b6f5.jpeg)
after
![622ee73c-bc82-4c7a-92fc-5ec9df6c119a](https://user-images.githubusercontent.com/23159587/221740886-7dd20a80-81ba-404b-9d74-641c93afbc44.jpeg)
the etcd client should connect the new leader not the old leader, and only send the request the leader redirectly.

**Comment by lhy1024** [comment]
I will fix it as soon as possible
