### ISSUE TITLE
"Not enough replicas" caused keyspace group split to fail randomly

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#6550]
### What did you do?
QA team ran keyspace group split with pd-ctl

### What did you expect to see?
keyspace group split should successfully complete

### What did you see instead?
Randomly failed because of "Not enough replicas" 

### What version of PD are you using (`pd-server -V`)?
tidbcloud/pd-cse release-6.6-keyspace 9e1e2de5194655c2e1224ce94057e7f7fb5f7eb4

**Comment by rleungx** [comment]
This is because the watcher is started before the bootstrap process. The alloc node loop exits since there is no group in etcd (introduced by https://github.com/tikv/pd/pull/6390). When the bootstrap process is trying to init the default group, it cannot be assigned the members, so it will persist the null to etcd which triggers the above problem.
