### ISSUE TITLE
region is not balanced during br restore

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#7148]
### What did you do?
1、command="export AWS_ACCESS_KEY_ID=minioadmin;export AWS_SECRET_ACCESS_KEY=minioadmin;/br restore db  --send-credentials-to-tikv=true --db tpcc20000 --pd http://tc-pd.endless-ha-test-with-some-feature-tps-2760236-1-101:2379 --storage s3://benchmark/tpcc20000 --s3.endpoint  http://minio.pingcap.net:9000 --check-requirements=false

### What did you expect to see?
region is balanced during br restore

### What did you see instead?
region is not balanced during br restore
![697e5e61-9453-4c4b-93b1-176e7eec52e5](https://github.com/tikv/pd/assets/84712107/2456acc5-c7bb-4260-a548-2210e7a9c7b0)

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: a21fd58d9953eeb8a4ff2657c04de2f44ee29e0e
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:  2023-09-22 11:36:18
2023-09-23T01:25:02.465+0800

**Comment by CabinfeverB** [comment]
affects 6.5.5

**Comment by CabinfeverB** [comment]
The BR suspends the merge scheduling operation by setting max-merge-region-size to 0.
Due to PR https://github.com/tikv/pd/pull/7009, the size of the region where the spilt occurs is 0.
So the BR failed to suspend the merge scheduling operation. After the split interval, regions are merged, which weakens scatter effect and results in unbalanced TiKV data (region score).

**Comment by CabinfeverB** [comment]
Workaround
Pause the schedule manually with the limit parameter. In pd-ctl:
> config set schedule.merge-schedule-limit 0

**Comment by CabinfeverB** [comment]
There may be a bug about size check after split, see https://github.com/tikv/tikv/issues/15696
